# Generated by Django 5.0.7 on 2024-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drinks', models.JSONField()),
                ('order_by', models.CharField(choices=[('현금', '현금'), ('송금', '송금'), ('쿠폰', '쿠폰')], max_length=3)),
            ],
        ),
    ]
